version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_cdc
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sales_db
    ports:
      - "5432:5432"
    networks:
      - sales_net

networks:
  sales_net:
    external: true 